### PR TITLE
✨ (expires): Add expires option to security.txt

### PR DESCRIPTION
**Pull request by NSpehler**
Hello @Vacilando 👋 

This PR adds the mandatory `Expires:` option to the generated security.txt file (see [here](https://www.rfc-editor.org/rfc/rfc9116#section-2.5.5)).

Please let me know if you have any feedbacks!

### CODE REVIEW

**Comment by NSpehler** [comment]
Hello @Vacilando, do you think we could merge this PR please?

**Comment by Vacilando** [comment]
Looks solid, @NSpehler, will review once back at desk next week.

**Comment by NSpehler** [comment]
Hello @Vacilando, did you get a chance to look into this? I'd love to see it merged ☺️

**Comment by Vacilando** [comment]
Merged, thanks, @NSpehler ✓

**Pull request merged**
